server:
  port: 8083

spring:
  profiles:
    active: test

---
spring:
  profiles: test
  kafka:
    template:
      default-topic: mensagem
    producer:
      bootstrap-servers: localhost:9092,localhost:9093
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      admin:
        properties:
          bootstrap.servers: localhost:9092,localhost:9093,localhost:9094

app:
  fornecedores:
    - nome: 
      codForncedor: 1234565667 
      urls:
        - endPoint: 
          chave: 